Added useBootstrap4 as an initialization parameter
brokenhandsio/SteamPress pull request #10
Opened 2017-04-12 13:23 UTC by timominous

Adding the `useBootstrap4` parameter so that it could be set through initialization or through the config file.

2017-04-12 13:35 UTC, 0xTim requested changes
Just a quick style change, other than that it looks really good!

2017-04-12 13:35 UTC, 0xTim commented on Sources/SteamPress/Provider.swift
> +        let useBootstrap4: Bool = config[Provider.configFilename, "paginator", "useBootstrap4"]?.bool ?? true
You don't need to specify the type (`:Bool`) here as it will infer it

2017-04-13 12:00 UTC, 0xTim approved these changes

2017-04-13 12:06 UTC, 0xTim commented
Could you try removing the Package.pins from your branch and removing it from the .gitignore - we probably don't want it in a library and I think that's the issues for the CI errors

2017-04-13 12:25 UTC, timominous commented
@0xTim Removed Package.pins but it wasn't on .gitignore. We'll see if the CI finishes up.

2017-04-13 12:36 UTC, 0xTim commented
Sorry meant adding it to the `.gitignore`! It shouldn't be in there and it will stop it getting checked in

2017-04-13 12:53 UTC, timominous commented
@0xTim Sure. Will add it to .gitignore now.

2017-04-13 12:54 UTC, 0xTim commented
Awesome looks like that has fixed the tests

2017-04-13 13:20 UTC, merged